"""Unit tests for checksum-manifest parsing, writing, and calculation."""

import os
import tempfile
import unittest

from bwverify.checksums import (
    ChecksumFileError,
    ChecksumEntry,
    VerificationCancelled,
    calculate_checksum,
    calculate_crc32,
    manifest_comments_and_style,
    parse_checksum_file,
    parse_sfv_file,
    write_checksum_file,
)
from bwverify.document import load_document, save_new_document, save_open_document
from bwverify.settings import ApplicationSettings, load_settings, save_settings


# Temporary files make parser, writer, and calculation tests independent of the checkout.
class ChecksumTests(unittest.TestCase):
    """Exercise public checksum helpers with temporary files."""

    def write_file(self, directory, name, contents, binary=False):
        """Create a temporary text or binary file and return its path."""
        path = os.path.join(directory, name)
        mode = "wb" if binary else "w"
        with open(path, mode) as handle:
            handle.write(contents)
        return path

    def test_parses_comments_and_filenames_with_spaces(self):
        """SFV comments do not prevent filenames with leading spaces parsing."""
        with tempfile.TemporaryDirectory() as directory:
            path = self.write_file(
                directory,
                "checks.sfv",
                "; Generated by bwVerify\n\n first file.bin abcdef12\nsecond.bin 00112233\n",
            )

            entries = parse_sfv_file(path)

        self.assertEqual(entries[0].filename, " first file.bin")
        self.assertEqual(entries[0].checksum, "ABCDEF12")
        self.assertEqual(entries[1].filename, "second.bin")

    def test_parses_hexadecimal_sfv_filenames_without_reversing_the_record(self):
        """An SFV filename may itself look like an eight-character checksum."""
        with tempfile.TemporaryDirectory() as directory:
            path = self.write_file(directory, "checks.sfv", "a1b2c3d4 01234567\n")

            entries = parse_sfv_file(path)

        self.assertEqual(entries, [ChecksumEntry("a1b2c3d4", "01234567", "CRC-32")])

    def test_parses_gnu_text_and_binary_separators(self):
        """GNU text and binary records retain the filename after their separator."""
        digest = "900150983cd24fb0d6963f7d28e17f72"
        with tempfile.TemporaryDirectory() as directory:
            path = self.write_file(
                directory,
                "checksums.md5",
                f"{digest}  text file.txt\n{digest} *binary file.txt\n",
            )

            entries = parse_checksum_file(path)

        self.assertEqual(entries[0], ChecksumEntry("text file.txt", digest.upper(), "MD5"))
        self.assertEqual(entries[1], ChecksumEntry("binary file.txt", digest.upper(), "MD5"))

    def test_rejects_invalid_records(self):
        """Malformed checksum records report a parsing error."""
        with tempfile.TemporaryDirectory() as directory:
            path = self.write_file(directory, "checks.sfv", "not an SFV record\n")

            with self.assertRaises(ChecksumFileError):
                parse_sfv_file(path)

    def test_parses_gnu_md5_and_bsd_sha256_records(self):
        """GNU and BSD records can be combined in one manifest."""
        with tempfile.TemporaryDirectory() as directory:
            path = self.write_file(
                directory,
                "checksums.txt",
                "900150983cd24fb0d6963f7d28e17f72  file.txt\n"
                "SHA256 (archive.tar) = "
                "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad\n",
            )

            entries = parse_checksum_file(path)

        self.assertEqual(entries[0].filename, "file.txt")
        self.assertEqual(entries[0].algorithm, "MD5")
        self.assertEqual(entries[1].filename, "archive.tar")
        self.assertEqual(entries[1].algorithm, "SHA-256")

    def test_parses_named_bsd_sha3_and_blake2_records(self):
        """Named BSD records select the algorithm rather than infer digest length."""
        with tempfile.TemporaryDirectory() as directory:
            path = self.write_file(
                directory,
                "checksums.txt",
                "SHA3-256 (file.txt) = " + "a" * 64 + "\n"
                "BLAKE2b (archive.tar) = " + "b" * 128 + "\n",
            )

            entries = parse_checksum_file(path)

        self.assertEqual(entries[0].algorithm, "SHA3-256")
        self.assertEqual(entries[1].algorithm, "BLAKE2B")

    def test_calculates_each_documented_hash_algorithm(self):
        """Every documented hashlib algorithm can calculate a known digest."""
        # These published vectors cover each algorithm exposed by the application.
        expected = {
            "MD5": "900150983CD24FB0D6963F7D28E17F72",
            "SHA-1": "A9993E364706816ABA3E25717850C26C9CD0D89D",
            "SHA-224": "23097D223405D8228642A477BDA255B32AADBCE4BDA0B3F7E36C9DA7",
            "SHA-256": "BA7816BF8F01CFEA414140DE5DAE2223B00361A396177A9CB410FF61F20015AD",
            "SHA-384": (
                "CB00753F45A35E8BB5A03D699AC65007272C32AB0EDED1631A8B605A43FF5BED"
                "8086072BA1E7CC2358BAECA134C825A7"
            ),
            "SHA-512": (
                "DDAF35A193617ABACC417349AE20413112E6FA4E89A97EA20A9EEEE64B55D39A"
                "2192992A274FC1A836BA3C23A3FEEBBD454D4423643CE80E2A9AC94FA54CA49F"
            ),
            "SHA3-224": "E642824C3F8CF24AD09234EE7D3C766FC9A3A5168D0C94AD73B46FDF",
            "SHA3-256": "3A985DA74FE225B2045C172D6BD390BD855F086E3E9D525B46BFE24511431532",
            "SHA3-384": (
                "EC01498288516FC926459F58E2C6AD8D"
                "F9B473CB0FC08C2596DA7CF0E49BE4B298D88CEA927AC7F539F1EDF228376D25"
            ),
            "SHA3-512": (
                "B751850B1A57168A5693CD924B6B096E"
                "08F621827444F70D884F5D0240D2712E10E116E9192AF3C91A7EC57647E39340"
                "57340B4CF408D5A56592F8274EEC53F0"
            ),
            "BLAKE2B": (
                "BA80A53F981C4D0D6A2797B69F12F6E9"
                "4C212F14685AC4B74B12BB6FDBFFA2D17D87C5392AAB792DC252D5DE4533CC95"
                "18D38AA8DBF1925AB92386EDD4009923"
            ),
            "BLAKE2S": "508C5E8C327C14E2E1A72BA34EEB452F37458B209ED63A294D999B4C86675982",
        }
        with tempfile.TemporaryDirectory() as directory:
            path = self.write_file(directory, "file.bin", b"abc", binary=True)

            for algorithm, checksum in expected.items():
                with self.subTest(algorithm=algorithm):
                    self.assertEqual(calculate_checksum(path, algorithm), checksum)

    def test_calculates_crc32_in_streaming_chunks(self):
        """Streaming calculations return known CRC-32 and SHA-256 digests."""
        with tempfile.TemporaryDirectory() as directory:
            path = self.write_file(directory, "file.bin", b"123456789", binary=True)

            self.assertEqual(calculate_crc32(path), "CBF43926")
            self.assertEqual(
                calculate_checksum(path, "SHA-256"),
                "15E2B0D3C33891EBB0F1EF609EC419420C20E320CE94C65FBC8C3312448EB225",
            )

    def test_stops_when_checksum_calculation_is_cancelled(self):
        """The cancellation callback stops a calculation before it completes."""
        with tempfile.TemporaryDirectory() as directory:
            path = self.write_file(directory, "file.bin", b"x" * 1024, binary=True)

            with self.assertRaises(VerificationCancelled):
                calculate_checksum(path, "SHA-256", lambda: True)

    def test_writes_and_reads_an_escaped_gnu_manifest(self):
        """GNU filename escaping survives a manifest write/read round trip."""
        with tempfile.TemporaryDirectory() as directory:
            source = self.write_file(directory, "file name.txt", b"abc", binary=True)
            manifest = os.path.join(directory, "checksums.sha256")
            entry = ChecksumEntry(
                "file\\name.txt", calculate_checksum(source, "SHA-256"), "SHA-256"
            )
            write_checksum_file(manifest, [entry])

            entries = parse_checksum_file(manifest)

        self.assertEqual(entries, [entry])

    def test_preserves_or_omits_comments_when_writing_a_manifest(self):
        """Comment retention is controlled by whether comments are supplied."""
        with tempfile.TemporaryDirectory() as directory:
            manifest = os.path.join(directory, "checks.sfv")
            entry = ChecksumEntry("file.bin", "CBF43926", "CRC-32")

            write_checksum_file(
                manifest, [entry], style="sfv", comments=["; created by test"]
            )
            comments, style = manifest_comments_and_style(manifest)
            self.assertEqual(comments, ["; created by test"])
            self.assertEqual(style, "sfv")

            write_checksum_file(manifest, [entry], style=style)
            comments, style = manifest_comments_and_style(manifest)
            self.assertEqual(comments, [])
            self.assertEqual(style, "sfv")

    def test_document_helpers_preserve_manifest_style_and_comments(self):
        """Document helpers keep metadata when an opened manifest is saved."""
        with tempfile.TemporaryDirectory() as directory:
            manifest = os.path.join(directory, "checks.sfv")
            write_checksum_file(
                manifest,
                [ChecksumEntry("file.bin", "CBF43926", "CRC-32")],
                style="sfv",
                comments=["; created by test"],
            )

            document = load_document(manifest)
            save_open_document(manifest, document.entries, document.style, document.comments)

            self.assertEqual(load_document(manifest), document)

    def test_document_helpers_apply_selected_encoding_and_line_endings(self):
        """New and opened manifests use the explicit output settings on every save."""
        with tempfile.TemporaryDirectory() as directory:
            manifest = os.path.join(directory, "checks.sfv")
            entry = ChecksumEntry("file.bin", "CBF43926", "CRC-32")

            save_open_document(
                manifest,
                [entry],
                "sfv",
                ["; comment"],
                encoding="utf-16",
                line_ending_identifier="crlf",
            )

            with open(manifest, "rb") as handle:
                contents = handle.read()
            self.assertTrue(contents.startswith((b"\xff\xfe", b"\xfe\xff")))
            self.assertIn("; comment\r\nfile.bin CBF43926\r\n", contents.decode("utf-16"))
            self.assertEqual(load_document(manifest).entries, [entry])

            save_new_document(
                manifest,
                [(os.path.join(directory, "file.bin"), "CBF43926", "CRC-32")],
                "sfv",
                encoding="latin-1",
                line_ending_identifier="cr",
            )
            with open(manifest, "rb") as handle:
                self.assertEqual(handle.read(), b"file.bin CBF43926\r")

    def test_new_document_writes_paths_relative_to_manifest(self):
        """New documents receive paths relative to their own output directory."""
        with tempfile.TemporaryDirectory() as directory:
            source_directory = os.path.join(directory, "source")
            os.mkdir(source_directory)
            source = self.write_file(source_directory, "file.bin", b"abc", binary=True)
            manifest = os.path.join(directory, "checksums.sha256")

            entries = save_new_document(
                manifest,
                [(source, calculate_checksum(source, "SHA-256"), "SHA-256")],
            )

            self.assertEqual(entries[0].filename, os.path.join("source", "file.bin"))
            self.assertEqual(load_document(manifest).entries, entries)

    def test_new_document_path_modes_control_stored_filenames(self):
        """New manifests can store relative, absolute, or basename-only filenames."""
        with tempfile.TemporaryDirectory() as directory:
            source_directory = os.path.join(directory, "source")
            os.mkdir(source_directory)
            source = self.write_file(source_directory, "file.bin", b"abc", binary=True)
            manifest = os.path.join(directory, "checksums.sfv")
            record = [(source, calculate_checksum(source, "CRC-32"), "CRC-32")]

            expected_filenames = {
                "relative": os.path.join("source", "file.bin"),
                "absolute": source,
                "filename": "file.bin",
            }
            for path_mode, expected_filename in expected_filenames.items():
                entries = save_new_document(manifest, record, "sfv", path_mode)
                self.assertEqual(entries[0].filename, expected_filename)
                self.assertEqual(load_document(manifest).entries, entries)

    def test_settings_round_trip_and_invalid_file_defaults(self):
        """Settings helpers retain valid values and safely fall back to defaults."""
        with tempfile.TemporaryDirectory() as directory:
            settings_path = os.path.join(directory, "config", "settings.conf")
            expected = ApplicationSettings(
                1024,
                768,
                directory,
                True,
                True,
                "bsd-sha256",
                "filename",
                "dark",
                "symbolic",
                "utf-16",
                "crlf",
            )
            save_settings(settings_path, expected)
            self.assertEqual(load_settings(settings_path), expected)

            with open(settings_path, "w", encoding="utf-8") as handle:
                handle.write("[preferences]\nicon_set = tango\n")
            self.assertEqual(load_settings(settings_path).icon_set, "tango")

            with open(settings_path, "w", encoding="utf-8") as handle:
                handle.write("[preferences]\nicon_set = unsupported\n")
            self.assertEqual(load_settings(settings_path).icon_set, "oxygen")

            with open(settings_path, "w", encoding="utf-8") as handle:
                handle.write(
                    "[preferences]\nfile_encoding = unsupported\nline_ending = unsupported\n"
                )
            values = load_settings(settings_path)
            self.assertEqual(values.file_encoding, "utf-8")
            self.assertEqual(values.line_ending, "lf")

            with open(settings_path, "w", encoding="utf-8") as handle:
                handle.write("[window]\nwidth = invalid\n")
            self.assertEqual(load_settings(settings_path), ApplicationSettings())

    def test_settings_loads_the_legacy_ini_file_when_conf_is_absent(self):
        """Renaming the settings file retains existing user preferences."""
        with tempfile.TemporaryDirectory() as directory:
            settings_path = os.path.join(directory, "config", "settings.conf")
            legacy_path = os.path.join(directory, "config", "settings.ini")
            expected = ApplicationSettings(theme="dark")

            save_settings(legacy_path, expected)

            self.assertEqual(load_settings(settings_path, legacy_path), expected)


if __name__ == "__main__":
    unittest.main()
